# Generated by Django 3.0.3 on 2020-07-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='movies')),
                ('category', models.CharField(choices=[('C', 'COMEDY'), ('R', 'ROMANCE'), ('D', 'DRAMA'), ('A', 'ACTION')], max_length=200)),
                ('language', models.CharField(choices=[('GR', 'GERMAN'), ('EN', 'ENGLISH')], max_length=200)),
                ('status', models.CharField(choices=[('RA', 'RECENTLY ADDED'), ('TR', 'TOP RATED'), ('MW', 'MOST WATCHED')], max_length=200)),
                ('year_of_production', models.DateField()),
                ('view_count', models.IntegerField(default=0)),
            ],
        ),
    ]
