# Generated by Django 3.0.3 on 2020-07-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('COMEDY', 'COMEDY'), ('ACTION', 'ACTION'), ('DRAMA', 'DRAMA'), ('ROMANCE', 'ROMANCE')], max_length=200),
        ),
    ]
