# Generated by Django 3.0.3 on 2020-08-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200809_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_trailer',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('Comedy', 'Comedy'), ('Action', 'Action'), ('romance', 'Romance'), ('Drama', 'Drama')], max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('RA', 'RECENTLY ADDED'), ('TR', 'TOP RATED'), ('MW', 'MOST WATCHED')], max_length=200),
        ),
    ]
