# Generated by Django 3.0.3 on 2020-08-09 12:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200809_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 9, 12, 4, 5, 157948, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('Comedy', 'Comedy'), ('romance', 'Romance'), ('Action', 'Action'), ('Drama', 'Drama')], max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('German', 'GERMAN'), ('English', 'ENGLISH')], max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('RA', 'RECENTLY ADDED'), ('MW', 'MOST WATCHED'), ('TR', 'TOP RATED')], max_length=200),
        ),
        migrations.AlterField(
            model_name='movielinks',
            name='type',
            field=models.CharField(choices=[('D', 'DOWNLOAD LINK'), ('W', 'WATCH LINK')], max_length=100),
        ),
    ]
